export const ROUTES = {
  home: "/",
  about: "/about-us",
  whyUs: "/why-us",
  services: "/services",
  portfolio: "/portfolio",
  contact: "/contact",
  caseStudies: "/case-studies",
  insuranceCaseStudy: "/case-studies/insurance",
  coffeeCaseStudy: "/case-studies/coffee",
  londonTravelCaseStudy: "/case-studies/london-travel",
  iotAssetCaseStudy: "/case-studies/iot-asset-monitoring",
  cloudDevopsCaseStudy: "/case-studies/cloud-devops-modernization",
  apiIntegrationCaseStudy: "/case-studies/api-integration-hub",
  customSoftware: "/custom-software",
  mobileApp: "/mobile-app",
  apiIntegrationSupport: "/api-integration-support",
  webApp: "/web-app",
  ecommerce: "/ecommerce",
  aiAutomation: "/ai-automation-integration",
  iotSolutions: "/iot-solutions",
  iosDevelopment: "/ios-development",
  androidDevelopment: "/android-development",
  digitalTransformation: "/digital-transformation",
  security: "/security",
  cloudDevops: "/cloud-devops",
  consulting: "/consulting",
  events: "/events",
  blog: "/blog",
  blogDetail: "/blog/:id",
};

export const getBlogDetailPath = (id: number | string) => `/blog/${id}`;

